### PR TITLE
Remove unused variables which cause build to fail under GCC

### LINKED ISSUE #136: GCC build fails with unused variable issue
**Describe the bug**
Related to #131 and #132, and probably caused by #129 - building under the GCC distributed with Ubuntu 18.04 results in a compile error due to unused variable warnings:

```
/home/travis/build/no2chem/concord-bft/bftengine/src/bftengine/ReplicaLoader.cpp: In function ‘bftEngine::impl::ReplicaLoader::ErrorCode bftEngine::impl::{anonymous}::loadViewInfo(bftEngine::impl::PersistentStorage*, bftEngine::impl::LoadedReplicaData&)’:
/home/travis/build/no2chem/concord-bft/bftengine/src/bftengine/ReplicaLoader.cpp:159:11: error: variable ‘initialViewNum’ set but not used [-Werror=unused-but-set-variable]
   ViewNum initialViewNum = 0;
           ^~~~~~~~~~~~~~
/home/travis/build/no2chem/concord-bft/bftengine/src/bftengine/ReplicaLoader.cpp:160:8: error: variable ‘isInView’ set but not used [-Werror=unused-but-set-variable]
   bool isInView = false;
        ^~~~~~~~
cc1plus: all warnings being treated as errors
```

**To Reproduce**
See this job:
https://travis-ci.com/no2chem/concord-bft/jobs/219173980

**Expected behavior**
The build should succeed

### PR DESCRIPTION
**Pull request by no2chem**
This PR removes unused variables in ```ReplicaLoader.cpp``` which were causing the build to fail with GCC using -Werror. It appears that these variables were being used to track intermediate state at some point (perhaps for debug?) and are no longer being used.

This PR fixes #136 and should be merged before accepting #135.

### CODE REVIEW

**Comment by andrewjstone** [comment]
These were already removed in #130.
